### ISSUE TITLE
Error: spawn git ENOENT

### ISSUE THREAD

**Issue by tawlang** [daisygao/daisygao.github.io#1]
为什么我搭建这个环境的时候，一直报这个错误？
E:\taolang>hexo deploy
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
INFO  Copying files from extend dirs...
'git'
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: spawn git ENOENT
    at notFoundError (E:\taolang\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (E:\taolang\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (E:\taolang\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

在windows 7 上搭建的，谢谢帮解答下吧

**Comment by Leader755** [comment]
我也遇到过了,求解
![image](https://user-images.githubusercontent.com/37180494/103144631-db37c180-4767-11eb-937a-a50f533c7b78.png)
